### ISSUE TITLE
need to parse math part

### ISSUE THREAD

**Issue by dannypsnl** [kentookura/tree-sitter-forester#1]
The `\li` in math expression `#{\lim_{x \to 0} f(x)}` also got highlighted as `\li{...}`.

**Comment by kentookura** [comment]
I wanted to set up language injections but didn't get around to it.
When we have this set up we can get syntax highlighting for latex embeddedi in tree files

https://tree-sitter.github.io/tree-sitter/syntax-highlighting#language-injection
https://github.com/DariusCorvus/tree-sitter-language-injection.nvim

**Comment by dannypsnl** [comment]
Another similar issue was \proof got parsed as \p as above; this is a defined block, I'm not sure if tree-sitter is able to solve these situations.

**Comment by kentookura** [comment]
Some oft this is actually an issue with the queries which are part of the neovim plugin.
Queries basically allow you to pattern match on a syntax tree, and the way they I implemented them in forester.nvim is not particularly sophisticated yet (matching strings).
The plan is to change the parser to use fields:  https://tree-sitter.github.io/tree-sitter/creating-parsers#using-fields
This will make pattern matching much easier and will alllow us to write better syntax highlighting

**Comment by kentookura** [comment]
See the new screenshot, the parser isn't perfect yet but much better than before
